name: Deploy to Cloudflare Pages and Workers

on:
  push:
    branches:
      - master  # 或者你的主分支11

jobs:
  deploy-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies for React app
        run: |
          cd src && npm install

      - name: Build React app
        run: |
          cd src && npm run build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: my-react-app  # 替换为你的Pages项目名称
          directory: build  # React应用的构建目录

  deploy-worker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Build Worker
        run: npm run build
        working-directory: myworker

      - name: Change directory to my-worker
        run: cd myworker  # 切换到my-worker目录

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: myworker
          entryPoint: index.js  # 指定入口文件
